#define MIDI_CC_BANK_SELECT_MSB     0x00
#define MIDI_CC_MODULATION_DEPTH    0x01
#define MIDI_CC_PORTAMENTO_TIME     0x05
#define MIDI_CC_DATA_ENTRY_MSB      0x06
#define MIDI_CC_CHANNEL_VOLUME      0x07
#define MIDI_CC_PANPORT             0x0a
#define MIDI_CC_EXPRESSION          0x0b
#define MIDI_CC_BANK_SELECT_LSB     0x20
#define MIDI_CC_DATA_ENTRY_LSB      0x26
#define MIDI_CC_SUSTAIN_DAMPER      0x40
#define MIDI_CC_PORTAMENTO          0x41
#define MIDI_CC_SOSTENUTO           0x42
#define MIDI_CC_SOFT_PEDAL          0x43
#define MIDI_CC_HARMONIC_CONTENT    0x47
#define MIDI_CC_RELEASE_TIME        0x48
#define MIDI_CC_ATTACK_TIME         0x49
#define MIDI_CC_BRIGHTNESS          0x4a
#define MIDI_CC_DECAY_TIME          0x4b
#define MIDI_CC_VIBRATO_RATE        0x4c

